import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Brighten School",
  description: "Generated by brighten team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>{children}</body>
    </html>
  );
}
